# Generated by Django 3.2.3 on 2021-05-22 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('isin', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('limit_price', models.FloatField(blank=True, null=True)),
                ('side', models.BooleanField()),
                ('valid_until', models.DateTimeField(db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now=True, db_index=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='OrdersApp.stock')),
            ],
        ),
    ]
