name: Terraform-GitHub-Actions
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'
#  pull_request:
#    branches: [ master ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
  TF_VAR_AWS_EC2_PEM: ${{ secrets.aws_ec2_pem }}
  TF_VAR_HASH: ${{ github.sha }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: success() && steps.findPr.outputs.number
        run: terraform plan
        env:
          TF_VAR_PR: ${{ steps.findPr.outputs.pr }}

      - name: Terraform Apply
        id: apply
        if: success() && steps.findPr.outputs.number
        run: terraform apply --auto-approve
        env:
          TF_VAR_PR: ${{ steps.findPr.outputs.pr }}