name: Terraform-GitHub-Actions
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'
#  pull_request:
#    branches: [ master ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
  TF_VAR_AWS_EC2_PEM: ${{ secrets.aws_ec2_pem }}
  TF_VAR_HASH: ${{ github.sha }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - run: echo "TF_VAR_PR=${{ steps.branch-name.outputs.base_ref_branch }} >> $GITHUB_ENV"
        if: success() && steps.findPr.outputs.number

      - name: Test PR env
        run: echo "Test -> PR is ${TF_VAR_PR}"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve